stages:
  - test

realizar_testes:
  stage: test
  image: node:17-alpine3.14
  before_script:
    - cd app/
    - npm install 
  script:
    - npm test
  ##gerar relatório
  artifacts:
  ##gerar sempre
    when: always
    reports:
    ##onde vai gerar com o padrão de xml
      junit: app/junit.xml